### ISSUE TITLE
Main menu » redSHOP » Frontpage category  = empty view.

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5240]
I am using the "redSHOP » Frontpage category" a my frontpage of the site. After i upgraded to RS 3.0 this view is a blank page page.

Template Management » frontpage_category   is still present with my code.

@hungredweb

**Comment by hoang-tran-redweb** [comment]
@Rmh1978 I fixed it this pull request.
https://github.com/redCOMPONENT-COM/redSHOP/pull/5149/commits/64a180385018c747bef826d41d22beb224c62e16

**Comment by Rmh1978** [comment]
I have the fixed code in my package and still have the issue.

**Comment by NguyenBao10** [comment]
hi @Rmh1978 , sorry we will fix it in this pr https://github.com/redCOMPONENT-COM/redSHOP/pull/5251 , please follow up it, you could apply to your site as soon as its merged

**Comment by Rmh1978** [comment]
I applied the code and the fix now works.

**Comment by NguyenBao10** [comment]
Great !
